name: Build release image

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    name: Build release image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/arisudesu-dev/maddy:${{ env.VERSION }}
          push: true
